default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  database: react_app
  username: root
  password: 123456

development:
  <<: *default
  variables:
    sql_mode: TRADITIONAL
  database: react_app

test:
  <<: *default

production:
  <<: *default
